sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
  - epmd -daemon
language: elixir
elixir:
    - 1.2.6
    - 1.3.2
otp_release:
    - 18.3
    - 19.0
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
